In [2]:
import numpy
import numpy as np

# Q1
Create a numpy array starting from 2 till 50 with a stepsize of 3.

In [15]:
x1=np.arange(51)[2:51:3]
print(x1)




[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47 50]


# Q2
Accept two lists of 5 elements each from the user.
Convert them to numpy arrays. Concatenate these arrays and print it. Also sort these arrays and print it.

In [18]:
l1=[]
print("1st list elements:")
for x in range(1,6):
    a=int(input())
    l1.append(a)

l2=[]
print("2nd list elements:")
for y in range(1,6):
    b=int(input())
    l2.append(b)
    
print("1st_list= " , l1)
print("2nd_list= " , l2)

array1=np.array(l1)
print("1st Array: ",array1)
array2=np.array(l2)
print("2nd Array: ",array2)
array3=np.concatenate((array1,array2))
print("Concatenated Array: ",array3)

sort_array1=np.sort(array1)
print("1st sort Array: ",sort_array1)
sort_array2=np.sort(array2)
print("2nd sort Array: ",sort_array2)
sort_array3=np.sort(array3)
print("3rd sort Array: ",sort_array3)

1st list elements:
0
3
2
1
4
2nd list elements:
5
6
8
7
9
1st_list=  [0, 3, 2, 1, 4]
2nd_list=  [5, 6, 8, 7, 9]
1st Array:  [0 3 2 1 4]
2nd Array:  [5 6 8 7 9]
Concatenated Array:  [0 3 2 1 4 5 6 8 7 9]
1st sort Array:  [0 1 2 3 4]
2nd sort Array:  [5 6 7 8 9]
3rd sort Array:  [0 1 2 3 4 5 6 7 8 9]


# Q3
Write a code snippet to find the dimensions of a ndarray and its size

In [19]:

arr = np.array( [[ 0, 1, 2],
                 [ 3, 4, 5],
                 [6, 7, 8]])

print("No. of dimensions: ", arr.ndim)
 

print("Shape of array: ", arr.shape)
 

print("Size of array: ", arr.size)

No. of dimensions:  2
Shape of array:  (3, 3)
Size of array:  9


# Q4
How to convert a 1D array into a 2D array? Demonstrate with the help of a code snippet
Hint: np.newaxis, np.expand_dims

In [23]:
arr = np.arange(int(input()))
print("Test 1D array (shape) :", arr.shape)

two_d_array_row = arr[np.newaxis]
print("Test 2D array for row is :", two_d_array_row.shape)

two_d_array_col = arr[:, np.newaxis]
print("Test 2D array for column is :", two_d_array_col.shape)

6
Test 1D array (shape) : (6,)
Test 2D array for row is : (1, 6)
Test 2D array for column is : (6, 1)


# Q5
Consider two square numpy arrays. Stack them vertically and horizontally.
Hint: Use vstack(), hstack()

In [28]:
arr1=np.array([ [1 ,2, 3] , [4, 5, 6] ,[7, 8, 9]])
arr2=np.array([ [11, 12, 13] , [14 , 15, 16] ,[17, 18, 19]])
sq_arr1=np.square(arr1)
sq_arr2=np.square(arr2)

out_arr1=np.vstack((sq_arr1,sq_arr2))
print(out_arr1)

out_arr2=np.hstack((sq_arr1,sq_arr2))
print(out_arr2)

[[  1   4   9]
 [ 16  25  36]
 [ 49  64  81]
 [121 144 169]
 [196 225 256]
 [289 324 361]]
[[  1   4   9 121 144 169]
 [ 16  25  36 196 225 256]
 [ 49  64  81 289 324 361]]


# Q6
How to get unique items and counts of unique items?

In [29]:
list = [0,1,2,2,3,4,5,5,6,7,7,8,9]
un_list =[]
for a in list:
    if a not in un_list:
         un_list.append(a)
print ("Unique list: \n", un_list)

l1=[]
count = 0
for i in list:
    if i not in l1:
        count +=1
        l1.append(i)
        
print ("count of items:",count)

Unique list: 
 [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
count of items: 10
